### ISSUE TITLE
Issue with windoys style linebreaks

### ISSUE THREAD

**Issue by remygrandin** [jhildenbiddle/docsify-tabs#1]
Hi,

I had a little issue with your plugin : the markdown files saved yith windows style linebreaks (\r\n) were not correctly detected and parsed. I fixed it by making a quick hack on the regexes :

        codeMarkup: new RegExp(/(```[\s\S]*?```)/gm),
        commentReplaceMarkup: new RegExp("\x3c!-- " + commentReplaceMark + " (.*) --\x3e"),
        tabBlockMarkup: /^(<!-+\s+tabs:\s*?start\s+-+>)[\r\n]+([\s|\S]*?)[\r\n]+(<!-+\s+tabs:\s*?end\s+-+>)/m,
        tabCommentMarkup: /^<!-+\s+tab:\s*(.*)\s+-+>[\r\n]+([\s\S]*?)[\r\n]+(?=<!-+\s+tabs?:)/m,
        tabHeadingMarkup: /^#{1,6}\s*[*_]{2}\s*(.*[^\s])\s*[*_]{2}[\r\n]+([\s\S]*?)(?=#{1,6}\s*[*_]{2}|<!-+\s+tabs:\s*?end\s+-+>)/m

Basicly replacing the `\n+` by `[\r\n]+`

I may have missed a spot but it seam to work for me this way 

Anyway, thanks for your great work !

**Comment by jhildenbiddle** [comment]
Good catch, @remygrandin. Completely forgot about Windows-style line terminators. 🤦‍♂️ 

Fixed in 1.0.5.
