### ISSUE TITLE
array index wrong

### ISSUE THREAD

**Issue by mpadinhabrandao** [jhildenbiddle/docsify-tabs#16]
hi, i think that array index is wrong to render tabs with comments
I tested reduce index 2 to 1 and index 3 to 1.

https://github.com/jhildenbiddle/docsify-tabs/blob/f6073bc1464f5d5f71d3af1610093850447d96da/src/js/index.js#L101

**Comment by jhildenbiddle** [comment]
Thanks for creating the issue, @mpadinhabrandao.

Your fix addresses a symptom of a larger issue: when support for indented tabsets was added in 1.1.0, I neglected to update the regular expression used to match comment-based tabsets as I did or heading-based tabsets.

I've addressed this issue and will push the fix in the next release.
