### ISSUE TITLE
How to change color or border ?

### ISSUE THREAD

**Issue by beraybentesen** [jhildenbiddle/docsify-tabs#2]
Is there any way to disable orange border when tab selected ? It's also appear in your examples.

**Comment by jhildenbiddle** [comment]
Hi @beraybentesen.

The border you are seeing is a combination of your browser's default "focus" style and your docisfy theme styles. The docsify-tabs plugin does not specify styles for the tab focus state.

You can override this style the same way you would any other style. For example, you could add the following to your `index.html`:

```css
.docsify-tabs__tab:focus {
  outline: none;
}
```

I wouldn't recommend removing the focus effect entirely though. Doing so has serious usability implications for folks navigating your site with the keyboard or accessibility devices.
