### ISSUE TITLE
Suggestion: Button ID

### ISSUE THREAD

**Issue by phuongbag** [jhildenbiddle/docsify-tabs#20]
I am trying to do something like button # ID when click to the link it will auto redirect to that button and that line ID

**Comment by jhildenbiddle** [comment]
@phuongbag --

I do not understand the issue. Is this a docsify or docsify-tabs issue you're referring to?

**Comment by phuongbag** [comment]
Sorry about that. I don't know how to explain this. Let me try my best.
-------
So currently, there are no way to redirect to a page with multiple tabs and open it. If I redirect to a word that using id it will redirect to that line but alway with the first tab. (ID mean #ID smt like heading ID in docsify)

So I want someway to redirect to a tab in a page at that line.

ID : i9 will redirect to heading with id i9 - If it in the second tab it just redirect to line 9 but with the first tab.
https://localhost/tab/test?id=i9

**Comment by phuongbag** [comment]
ping - pong

**Comment by jhildenbiddle** [comment]
Understood.

You're asking for a tab that contains an element matching the "id" URL parameter to be auto-selected so that the content is visible on page load. Makes sense. Added to the backlog.

**Comment by phuongbag** [comment]
thanks

**Comment by jhildenbiddle** [comment]
Feature added in 1.3.0
