### ISSUE TITLE
Tab is not displayed when id contains url encoded characters

### ISSUE THREAD

**Issue by taiking** [jhildenbiddle/docsify-tabs#22]
hi, I found a bug according to the title.

For example, if you go directly to the URL below, the tab will not be displayed.
`http://localhost:3000/#/hoge?id=%e3%81%82`

It worked in version 1.2.0, but not in 1.3.0 or later.

JavaScript throws an error in the following part
https://github.com/jhildenbiddle/docsify-tabs/blob/3c8c6f95349c1786a27abd6b7698e89b72d4321e/src/js/index.js#L240

**Comment by jhildenbiddle** [comment]
@taiking —

Can you share a link to the site or the markdown that demonstrates the error? That will make it easier to verify that the bug has been fixed during development.

Thanks!

**Comment by jhildenbiddle** [comment]
Fixed in 1.4.1

Thanks for filing the issue, @taiking.

**Comment by taiking** [comment]
Thank you!
