### ISSUE TITLE
Scroll position on long pages

### ISSUE THREAD

**Issue by lfarrowhifi** [jhildenbiddle/docsify-tabs#25]
First off, thanks for making this plugin!

While we've been using docsify and this plugin for our documentation we've noticed that following anchors to specific sections on longer pages doesn't properly navigate you to that section (e.g. https://yuzudocs.balanced.dev/#/definition/markup?id=enum). Turning off docsify-tabs however remedies this problem as content is no longer disappearing into tabs.

Not sure if I'm missing the obvious solution or not, but is there anything that could be done to maintain the scroll position after docsify-tabs has finished arranging content? 

If not we may just split out our content into multiple pages so the issue is less pronounced, or if we're desperate we'll just try something along the lines of adding a custom plugin to the docsify setup with a horrible `setTimeout` with an arbitrary 1 second value to wait for the page & docsify-tabs to fully load, then scroll to the correct section.
```
plugins: [
  function (hook, vm) {
    hook.doneEach(function () {
      const id = vm.route.query.id;
      const element = id ? document.querySelector(`[data-id="${id}"]`) : undefined;
      if (element) {
        setTimeout(function() {
          element.scrollIntoView();
        }, 1000);
      }
    });
  }
]
```
Thanks in advance

**Comment by jhildenbiddle** [comment]
Hey @lfarrowhifi --

This is a known docsify issue that I covered here: https://github.com/jhildenbiddle/docsify-tabs/issues/8#issuecomment-580074636

Probably not the answer you were hoping for, but hopefully this explains the situation a bit. Long story short is that this fix needs to be added to docsify, not a plugin (like docsify-tabs) or theme (like docsify-themeable).
