### ISSUE TITLE
There is a bug in the tabcomments

### ISSUE THREAD

**Issue by popdo** [jhildenbiddle/docsify-tabs#29]
Examples

````markdown
<!-- tabs:start -->

<!-- tab:title1 -->

```css
.aa{color:#aaa}
```

<!-- tab:title2 -->

bbb

<!-- tabs:end -->
````

After tabs uses HTML comments, the code block will be parsed incorrectly, resulting in page display disorder.

**Comment by jhildenbiddle** [comment]
Thanks for filing the issue, @popdo. All fixed in 1.4.4.
