### ISSUE TITLE
Tabs not working in embedded markdown files

### ISSUE THREAD

**Issue by wkande** [jhildenbiddle/docsify-tabs#31]
With docsify 4.6 it is now possible to embed any type of file, including a markdown file.

If a tab-set is added to the parent file it works fine. However a tab-set added to an embedded file does not render.

**tabs-main.md**

```
# tabs-main.md

<!-- tabs:start -->

#### ** English **

Hello!

<!-- tabs:end -->

[filename](tabs-include.md ':include')
```

**tabs-include.md**

```
# tabs-include.md

<!-- tabs:start -->

#### ** English **

Hello!

<!-- tabs:end -->
```

### I have included a screen shot of the  results I get.

![Screen Shot 2020-10-08 at 3 30 53 PM](https://user-images.githubusercontent.com/3522283/95515724-4fd63d80-097b-11eb-91ab-fcb75ead1b13.png)

**Comment by jhildenbiddle** [comment]
Thanks for the suggestion, @wkande.

Unfortunately, this is a limitation of docsify's plugin system and not something that docsify-tabs can easily resolve. The short explanation is that docsify's plugin system function at the page level, so there is no "hook" to leverage for processing content that is loaded via an embed.

If you're interested in seeing this feature added to docsify, I recommend creating [a docsify issue](https://github.com/docsifyjs/docsify/issues) and referencing this issue to serve as an example.

Thanks!
