### ISSUE TITLE
[Bug] tabs not work when config homepage and basePath

### ISSUE THREAD

**Issue by ngthtung** [jhildenbiddle/docsify-tabs#33]
Hello, I'm using docsify-tabs follow config: ( but when i try to get file from local, it work )
```
window.$docsify = {
        loadSidebar: true,
        notFoundPage: "404.md",
        homepage: "https://ngthtung.github.io/docs/README.md",
        basePath: "https://raw.githubusercontent.com/ngthtung/docs/master/",
        subMaxLevel: 2,
        tabs: {
          persist: true, // default
          sync: true, // default
          theme: "classic", // default
          tabComments: true, // default
          tabHeadings: true // default
        }
      };
```
And tabs not working:
![image](https://user-images.githubusercontent.com/43090730/96957137-09a8de80-1524-11eb-869e-eb8e9d3f5076.png)

this is my demo:
https://gqhzr.csb.app/#/test.md

**Comment by jhildenbiddle** [comment]
Hi @ngthtung.

This appears to be an issue with docsify, not docsify-tabs.

I played with your demo a bit, and the issue appears to be related to the `basePath` option. When I disable it, docsify-tabs render as expected. My suggestion is that you create [a docsify issue](https://github.com/docsifyjs/docsify/issues) and reference this issue to serve as an example.

Thanks!

**Comment by calumk** [comment]
Opened issue : https://github.com/docsifyjs/docsify/issues/1711
