### ISSUE TITLE
Tab titles aren't processed by the markdown compiler

### ISSUE THREAD

**Issue by jcayzac** [jhildenbiddle/docsify-tabs#38]
```
<!-- tab:Example **manifest.webmanifest** -->
```

Doesn't render as `Example <strong>manifest.webmanifest</strong>`, but as `Example **manifest.webmanifest**`. Using the "bold heading" method also ignores any markup.

**Comment by jhildenbiddle** [comment]
Thanks, @jcayzac. I'll take a look.

**Comment by jhildenbiddle** [comment]
@jcayzac --

This issue has been addressed in 1.5.0. Details are available in the updated [Custom Styles](https://jhildenbiddle.github.io/docsify-tabs/#/?id=custom-styles) section of the docs.
