### ISSUE TITLE
Tab not working in my case

### ISSUE THREAD

**Issue by chandan-24** [jhildenbiddle/docsify-tabs#39]
Hi, tabs are not working in my case.
attaching the screenshots.

![Screenshot from 2021-01-03 10-35-10](https://user-images.githubusercontent.com/27084297/103472144-e1edb680-4daf-11eb-9eac-78967bed16c0.png)

![Screenshot from 2021-01-03 10-35-01](https://user-images.githubusercontent.com/27084297/103472153-0184df00-4db0-11eb-9f41-918cf5a35fc9.png)

![Screenshot from 2021-01-03 10-34-48](https://user-images.githubusercontent.com/27084297/103472154-034ea280-4db0-11eb-97c9-85e52386edf6.png)

**Comment by jhildenbiddle** [comment]
Have you included the docsify-tabs script and CSS on your `index.html` per the instructions in the [docs](https://jhildenbiddle.github.io/docsify-tabs/#/?id=installation)?

**Comment by chandan-24** [comment]
Yes, I had followed the docs.
