### ISSUE TITLE
 I need your help,using this plug-in, refresh, can not locate the exact location of the page

### ISSUE THREAD

**Issue by ayjw** [jhildenbiddle/docsify-tabs#40]
Can you support the refresh to locate the specific location of the page, or tell me the solution?

**Comment by jhildenbiddle** [comment]
Please see [this comment](https://github.com/jhildenbiddle/docsify-tabs/issues/8#issuecomment-580074636). 

TL;DR: It is an issue with how doscify (and browsers in general) handles anchor links. A proper fix would require an update fo docsify, not this plugin.
