### ISSUE TITLE
access document link ‘?Id=xxx’ positioning problem

### ISSUE THREAD

**Issue by Developer-Tang** [jhildenbiddle/docsify-tabs#50]
Directly accessing through the link will cause the title positioning to be lower...

example link: 
http://locaohost:3000/#/xxx?id=title4

md: 
```
## title1
.....
<!-- tabs:start -->
## **title2**
.....
## **title3**
.....
<!-- tabs:end -->
## title4
```

It is OK to access title 1 through the link, but the location of title 4 will be inaccurate. And the title in the tab cannot be located and displayed in the table of contents

**Comment by Niek** [comment]
I can confirm this issue. In addition, when two tabs have the same name on one page, switching the bottom one will jump to the top one.
