### ISSUE TITLE
Tabs unselected when changing pages

### ISSUE THREAD

**Issue by AntoineB9** [jhildenbiddle/docsify-tabs#51]
Hello,

First of all, thanks for everything you've done for Docsify !!

I recently updated "Docsify-tabs" from v1.4.4 to v1.6.0 and encountered an issue.
I have a two tabs set-up on a page that appears selected with the class "docsify-tabs__tab docsify-tabs__tab--active", but when browsing to another page and coming back, both tabs appears unselected (class "docsify-tabs__content").
Would anyone have any general idea that could be causing this ?

In case of: 
I'm using the "vue" theme and running those plugins : 
* Pagescroll
* Search
* Zoom_image
* Alerts
* Tabs
* Copycode
* Toc

I will continue to look into this issue and will update if I find anything.

Thanks :)

**Comment by thediveo** [comment]
Same issue here, with different theme, so this looks like a more general issue.

**Comment by jhildenbiddle** [comment]
Unable to reproduce this issue. If this is still an issue, let me know and we can investigate further.

**Comment by thediveo** [comment]
Firefox/Fennec on Android.

Navigate to https://edgeshark.siemens.io/#/getting-started, there are two tab sets on the page. Change one of the two sets to display a different tab. Hit Refresh. Now both tab sets have lost their active tabs.

**Comment by jhildenbiddle** [comment]
Thanks, @thediveo. Issue confirmed. I'll fork the repo and dive into the `/docs` directory as soon as I can.

**Comment by jhildenbiddle** [comment]
Fixed in v1.6.2.

**Comment by thediveo** [comment]
Yes, works also for me (for the moment we need to force using v1.6.2 explicitly, it's a pain that jsdelivr doesn't support minimum versions within the range inside a major)

**Comment by jhildenbiddle** [comment]
@thediveo --

I did a bit of research and discovered that jsdelivr has a CDN cache purge API and web interface:

- API: https://www.jsdelivr.com/documentation#id-purge-cache
- Web: https://www.jsdelivr.com/tools/purge

I was unaware of this until today, but I will make a point of purging the CDN cache after each new release. I went ahead and did this for the `@latest`, `@1`, and `@1.6` docsify-tabs URL aliases, so you _should_ be able to revet back to the `@1` aliases and load the latest version.
