### ISSUE TITLE
Error when in quote

### ISSUE THREAD

**Issue by SnowCutieOwO** [jhildenbiddle/docsify-tabs#56]
if you put tabs in the quote, its style will get broken

**Comment by jhildenbiddle** [comment]
Hi @SnowCutieOwO.

I don't think I understand the issue as described. Can you provide a code example?

**Comment by SnowCutieOwO** [comment]
> Hi @SnowCutieOwO.
> 
> I don't think I understand the issue as described. Can you provide a code example?

Sure! I will write a example here:

```
> This is a quote bar, hey!
> <!-- tabs:start -->
> #### **First Content Here!**
> Some contents...
> #### **Second Content Here!**
> Some contents...
> <!-- tabs:end -->
```

And this behaves weirdly, for example the style of tab cards dropped, and it cannot work properly, break the part in quote.

**Comment by jhildenbiddle** [comment]
Thanks for the follow-up. The plugin currently does not support tabs within quote blocks. To be honest, it is unlikely that I will add this feature anytime soon.

**Comment by SnowCutieOwO** [comment]
> Thanks for the follow-up. The plugin currently does not support tabs within quote blocks. To be honest, it is unlikely that I will add this feature anytime soon.

Thanks, quite a pity :(
