### ISSUE TITLE
Can we independently control the label synchronization switching function?

### ISSUE THREAD

**Issue by Developer-Tang** [jhildenbiddle/docsify-tabs#57]
Due to the use of multiple "tags" in the note and different content lengths, there may be a problem of view jumping up and down during the synchronization switching process. Can this feature be disabled separately in specific note? (tabs.sync)

In addition, this plugin is quite good. Thank you to the author for sharing it.

**Comment by jhildenbiddle** [comment]
Hi @Developer-Tang.

The plugin already handles scroll position changes that might occur as a result of auto-switching synced tabs. The scroll position is stored before tab switching occurs and is then restored after tab switching is complete.

If you are referring to a different issue, sharing a demo video or site that demonstrates the problem will be helpful.

**Comment by Developer-Tang** [comment]
This should be the issue you mentioned. If you can access this address, you can try switching the tags below it to reproduce the problem. This question comes from the content of the title "ConcurrentHashMap"

https://www.tangshh.cn/#/Java/JavaSE/%E9%9B%86%E5%90%88%E6%A1%86%E6%9E%B6?id=concurrenthashmap
